# Generated by Django 4.2 on 2023-04-07 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('multipoint', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('multilinestring', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geometrycollection', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
            ],
        ),
    ]
